### ISSUE TITLE
Version of hibernate packaged with app does not contain required functionality

### ISSUE THREAD

**Issue by ryanhardy** [NESCent/plhdb#20]
The version of hibernate3 packaged with the application (plhdb/WebRoot/WEB-INF/lib/hibernate3.jar, version 3.0.5) does not contain the functionality to allow "Thread Local Sessions" (this was only available in 3.1+), but the application is configured to use them rather than JTA sessions (plhdb/src/hibernate.cfg.xml.template).

**Comment by ryanhardy** [comment]
Creating different pull request for this.

**Comment by hlapp** [comment]
This is an issue, not a pull request, and it's a valid one, so fine to keep open until resolved.

**Comment by hlapp** [comment]
Fixed in 2e86bd6648ede352772bb1f11dc3a57cb5225ca1.
