### ISSUE TITLE
Update the PostgreSQL JDBC driver to 9.4

### ISSUE THREAD

**Issue by ryanhardy** [NESCent/plhdb#22]
The JDBC driver should be updated to 9.4's version. This should be backwards compatible with older version of PostgreSQL but should provide improvements in various ways on newer versions of the database.

**Comment by ryanhardy** [comment]
Creating a different pull request for this.

**Comment by hlapp** [comment]
This is an issue and hence is fine to leave open until addressed.

**Comment by hlapp** [comment]
Fixed in c8966e12cf6f82686a83adb438afd0042ee38da1.
