### ISSUE TITLE
SMTP server is hard-coded to NESCent server

### ISSUE THREAD

**Issue by ryanhardy** [NESCent/plhdb#24]
The SMTP server used for e-mail is hard-coded to smtp.nescent.org, which will be going away soon.  It should be replaced with "smtp.duke.edu" which is the standard Duke internal relay.

**Comment by hlapp** [comment]
New SMTP server set in 15a61ddbf3cab9a6a285b28db86160ec155d30bc, although this doesn't fix the fact that it's hardcoded.
