### ISSUE TITLE
JS files are not included in repository

### ISSUE THREAD

**Issue by ryanhardy** [NESCent/plhdb#25]
There are a number of javascript and CSS files that are called by the various templates but are not included in the repository.  The ones I've identified are these:

WebRoot/js
WebRoot/js/dojo
WebRoot/js/dojo/_base.js
WebRoot/js/dojo/dojo.js
WebRoot/js/dojo/_base
WebRoot/js/dojo/_base/_loader
WebRoot/js/dojo/_base/_loader/bootstrap.js
WebRoot/js/dojo/_base/_loader/hostenv_browser.js
WebRoot/js/dojo/_base/_loader/loader.js
WebRoot/js/dojo/_base/lang.js
WebRoot/js/dojo/parser.js
WebRoot/js/dijit
WebRoot/js/dijit/dijit.js
WebRoot/js/dijit/themes
WebRoot/js/dijit/themes/tundra
WebRoot/js/dijit/themes/tundra/tundra.css
WebRoot/js/dijit/_base.js

However, the page is still not able to load the following javascript (errors in the console), even though the files are there.  Perhaps there is some sort of path issue:

[Error] Error: Could not load 'dojo._base.lang'; last tried './_base/lang.js'
	_loadModule (loader.js, line 315)
	global code (_base.js, line 2)
[Error] Error: Could not load 'dijit._base'; last tried '../dijit/_base.js'
	_loadModule (loader.js, line 315)
	global code (dijit.js, line 4)
[Error] Error: Could not load 'dojo.parser'; last tried './parser.js'
	_loadModule (loader.js, line 315)
	global code (edit.go, line 150)

**Comment by hlapp** [comment]
The deploy script has the following lines in addition to a repository checkout:

```sh
cd $WORKSPACE/WebRoot
svn export --force --quiet http://svn.dojotoolkit.org/src/tags/release-0.9.0 js
```

(`$WORKSPACE` is set by Jenkins/Hudson to what you assume it is.)

I don't know why that is separate, and whether or not it has to be or couldn't just also be added to the repository. What's slightly concerning is that [Dojo doesn't advertise this way of downloading the toolkit anymore](http://dojotoolkit.org/download/), and v0.9.0 doesn't seem to be among the [available legacy versions](http://download.dojotoolkit.org/).

**Comment by ryanhardy** [comment]
I tried adding all the code from dojo 1.10.4 to my fork and building it this morning, and it seems to have corrected the oddity I was seeing.  There is one warning about synchronous XHR, but I think that’s just a deprecation warning rather than a problem.

Should I add a pull request for that, or shall I have the working group take a look to see if anything else still looks amiss?
