### ISSUE TITLE
Need continuously valid contact address for sending emails 

### ISSUE THREAD

**Issue by hlapp** [NESCent/plhdb#26]
The application sends emails, for example to reset a lost password. Emails must have a `From:` address. Currently this is help _at_ nescent _dot_ org. We can make this a noreply@plhdb.org address (in which case we need to make sure the MX settings exist and are valid for the domain lest such emails are rejected as spam), or a valid return address that someone can turn to. 

Contact emails are very easy to create using Duke's Sympa server, so I recommend doing that.

**Comment by hlapp** [comment]
@jbgordon85 and @ryanhardy - could you please discuss with Susan.

**Comment by jbgordon85** [comment]
I talked about it with Susan.  We don't particularly care what the new address actually is, so long as there is one.  I've emailed Ryan about it, and I assume he's taking care of it.
