### ISSUE TITLE
Make content changes to remove references from NESCent

### ISSUE THREAD

**Issue by ryanhardy** [NESCent/plhdb#27]
Susan/Jake requested the following changes:

1. Remove from home page: 
• NESCent award page of the working group
• National Evolutionary Synthesis Center (NESCent)

2. On the About page:
• The website is maintained by:
Remove NESCent, replace with Biology Department, Duke University
Address, no phone numbers

Credits:
• Concept, content, and scientific requirements: the Primate Life Histories Working Group, Susan C Alberts (Duke University, PI), Karen B Strier (University of Wisconsin-Madison, PI)

3. Available downloads:
Remove all the blue linked lines but leave the heading

**Comment by ryanhardy** [comment]
Was decided that Removal of NESCent-based links was not necessary.

**Comment by ryanhardy** [comment]
Typo, will open another pull request.

**Comment by ryanhardy** [comment]
Pull request should address the removal of available download links.

**Comment by hlapp** [comment]
I think this is complete now. Reopen if not.
